name: Your New Jekyll Site
markdown: redcarpet
pygments: true

assets:
  cache: true
  js_compressor: uglifier
  css_compressor: sass
  gzip: false

exclude:
  - Gemfile
  - Gemfile.lock
  - bin
  - vendor
  - bower.json
  - bower_components
