# Site settings
title: Fiatalok Jézusért Konferencia
email: info@fjk.hu
description: >
  Az FJK egy fiatalok által fiataloknak szervezett adventista konferencia. Az évente megrendezésre
  kerülő eseményen az előadások, szemináriumok és a találkozási lehetőségek a résztvevő ifjakat hitük
  megújítására, életük megreformálására és a Hetednapi Adventista Egyház tevékeny támogatására
  buzdítják, hogy a Hármas Angyali Üzenet ennek a generációnak a segítségével eljuthasson az egész
  világra.
baseurl: '' # the subpath of your site, e.g. /blog/
url: 'https://fjk.hu' # the base hostname & protocol for your site

# Build settings
markdown: kramdown

exclude: [
  'node_module',
  'bower_components',
  'Gruntfile.js',
  'package.json',
  'README.md',
  'bower.json',
  'tasks'
]

languages: ['hu', 'en']
exclude_from_localizations: ['assets']
